BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "account" (
	"id"	INTEGER NOT NULL DEFAULT 1 UNIQUE,
	"login"	TEXT NOT NULL UNIQUE,
	"pas"	TEXT NOT NULL,
	"email"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
